[package]
name = "rust-zmq"
version = "0.1.0"
authors = ["Jakub Beránek <berykubik@gmail.com>"]
edition = "2018"

[dependencies]
ureq = ""
serde = { version = "1.0.126", features = ["derive"] }
serde_json = ""
